### ISSUE TITLE
a dump file update enhancement suggestion

### ISSUE THREAD

**Issue by Sadi58** [techtacoriginal/offlinebay#12]
Unfortunately, I cannot access thepiratebay.org directly - I have to use either a VPN addon in my Firefox web browser, which fails to download the dump file after several megabytes, or a DNS server, and even then thepiratebay.org server often gives error, and I can only access the site's latest snapshot provided by "Cloudflare's Always Online™ technology", but downloading the dump file is istill impossible.

I think OfflineBay could be a good alternative for such cases as well if it automatically attempted to connect to mirror sites and even, as a last resort, provided the latest dump file hosted directly in this project repository.

I hope you can implement this suggestion as it would be a real relief to many users, I guess.

Thanks a lot.

**Comment by techtacoriginal** [comment]
This will not happen because I've already provided an easy option to run mirrors. It's up to enthusiastic users to run mirrors. Program already supports auto updates of dump. Let's not compromise the value and availability of the program by adding "Nasties" to the repo. Thanks for the suggestion. Keep 'em coming. Closing the issue.
